[project]
name = "mcpserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp-openai>=0.2.0",
    "mcp[cli]>=1.9.2",
]
